export const ORDER_REQUEST = "ORDER_REQUEST"
export const ORDER_REQUEST_SUCCESS = "ORDER_REQUEST_SUCCESS"
export const ORDER_REQUEST_FAIL = "ORDER_REQUEST_FAIL"
// export const ORDER_EMPTY = []

export const ORDER_REMOVE_PLACEORDER = "ORDER_REMOVE_PLACEORDER"
